// Auto-generated by sc-meta on first build.
// This placeholder will be replaced with the correct endpoint wiring.
// Run `sc-meta all build` from the project root to regenerate.

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    bulletin_board
    (
        init => init
        upgrade => upgrade
        createPost => create_post
        replyToPost => reply_to_post
        getPost => get_post
        getLatestPosts => get_latest_posts
        getLatestPostsFull => get_latest_posts_full
        getReplies => get_replies
        getPostCount => get_post_count
        getBoardStats => get_board_stats
        upvotePost => upvote_post
        getUpvotes => get_upvotes
    )
}
